# Clear DST dir from pybind
file(GLOB PYBIND_ARTIFACTS ${PYTHON_BINARY_DST}/pybind*)

if (NOT "${PYBIND_ARTIFACTS}" STREQUAL "")
    file(REMOVE_RECURSE ${PYBIND_ARTIFACTS})
endif()

# Copy Python-bindings
file(INSTALL ${PYTHON_BINARY_DIR}/
        DESTINATION ${PYTHON_BINARY_DST}/)