[tool.cibuildwheel]
build = "cp*"
archs = "auto64"
before-build = "bash tools/unix-wheels.sh"
build-verbosity = 1
test-requires = ["pytest", "numpy==1.24.4"]
test-command = "pytest {package}/tests"

[tool.cibuildwheel.linux]
build = "cp*-manylinux*"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

[tool.cibuildwheel.windows]
before-build = "python tools\\windows-wheels.py"